version: '3'
services:
  db:
    image: wangxian/alpine-mysql
    environment:
      MYSQL_DATABASE: $GW_MYSQL_DATABASE
      MYSQL_USER: $GW_MYSQL_USER
      MYSQL_PASSWORD: $GW_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $GW_MYSQL_PASSWORD

    restart: always
    ports:
      - $GW_MYSQL_PORT:3306

    volumes:
      - $GW_APP_STORAGE:/app:rw

  backend:
    image:  zenika/alpine-maven:3-jdk8
    environment:
      GW_MYSQL_HOST: db
      GW_MYSQL_PORT: 3306
      GW_MYSQL_DATABASE: $GW_MYSQL_DATABASE
      GW_MYSQL_USER: $GW_MYSQL_USER
      GW_MYSQL_PASSWORD: $GW_MYSQL_PASSWORD

    volumes:
      - .:/usr/src/app
      - $GW_MAVEN_M2_DIR:/root/.m2
    working_dir: /usr/src/app
    ports:
      - $GW_BACKEND_PORT:8080
    command: mvn clean spring-boot:run
    depends_on:
      - db
